version: "3"
services:
  refund_mat:
    image: ecodock/refund_mat
    container_name: refund_mat
    expose:
      - 80
      - 443
    restart: always
    environment:
      - VIRTUAL_HOST=refund.ecomundo.edu.ec
      - LETSENCRYPT_HOST=refund.ecomundo.edu.ec
      - LETSENCRYPT_EMAIL=info@ecomundo.edu.ec


networks:
  default:
    external:
      name: nginx-proxy
   